/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor.index'
import { Route as StudentWellbeingRouteImport } from './routes/student.wellbeing'
import { Route as StudentReadinessRouteImport } from './routes/student.readiness'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentJourneyRouteImport } from './routes/student.journey'
import { Route as StudentCompanionRouteImport } from './routes/student.companion'
import { Route as StudentCommunityRouteImport } from './routes/student.community'
import { Route as AdvisorStudentsRouteImport } from './routes/advisor.students'
import { Route as AdvisorRiskRouteImport } from './routes/advisor.risk'
import { Route as AdvisorReportsRouteImport } from './routes/advisor.reports'
import { Route as AdvisorInterventionsRouteImport } from './routes/advisor.interventions'
import { Route as StudentReadinessReportRouteImport } from './routes/student.readiness.report'
import { Route as AdvisorStudentsIdRouteImport } from './routes/advisor.students.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvisorRoute,
} as any)
const StudentWellbeingRoute = StudentWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReadinessRoute = StudentReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentJourneyRoute = StudentJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCompanionRoute = StudentCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCommunityRoute = StudentCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => StudentRoute,
} as any)
const AdvisorStudentsRoute = AdvisorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorRiskRoute = AdvisorRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorReportsRoute = AdvisorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorInterventionsRoute = AdvisorInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AdvisorRoute,
} as any)
const StudentReadinessReportRoute = StudentReadinessReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => StudentReadinessRoute,
} as any)
const AdvisorStudentsIdRoute = AdvisorStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdvisorStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/advisor/interventions': typeof AdvisorInterventionsRoute
  '/advisor/reports': typeof AdvisorReportsRoute
  '/advisor/risk': typeof AdvisorRiskRoute
  '/advisor/students': typeof AdvisorStudentsRouteWithChildren
  '/student/community': typeof StudentCommunityRoute
  '/student/companion': typeof StudentCompanionRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/readiness': typeof StudentReadinessRouteWithChildren
  '/student/wellbeing': typeof StudentWellbeingRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/advisor/students/$id': typeof AdvisorStudentsIdRoute
  '/student/readiness/report': typeof StudentReadinessReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/advisor/interventions': typeof AdvisorInterventionsRoute
  '/advisor/reports': typeof AdvisorReportsRoute
  '/advisor/risk': typeof AdvisorRiskRoute
  '/advisor/students': typeof AdvisorStudentsRouteWithChildren
  '/student/community': typeof StudentCommunityRoute
  '/student/companion': typeof StudentCompanionRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/readiness': typeof StudentReadinessRouteWithChildren
  '/student/wellbeing': typeof StudentWellbeingRoute
  '/advisor': typeof AdvisorIndexRoute
  '/student': typeof StudentIndexRoute
  '/advisor/students/$id': typeof AdvisorStudentsIdRoute
  '/student/readiness/report': typeof StudentReadinessReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/advisor/interventions': typeof AdvisorInterventionsRoute
  '/advisor/reports': typeof AdvisorReportsRoute
  '/advisor/risk': typeof AdvisorRiskRoute
  '/advisor/students': typeof AdvisorStudentsRouteWithChildren
  '/student/community': typeof StudentCommunityRoute
  '/student/companion': typeof StudentCompanionRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/readiness': typeof StudentReadinessRouteWithChildren
  '/student/wellbeing': typeof StudentWellbeingRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/advisor/students/$id': typeof AdvisorStudentsIdRoute
  '/student/readiness/report': typeof StudentReadinessReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/login'
    | '/signup'
    | '/student'
    | '/advisor/interventions'
    | '/advisor/reports'
    | '/advisor/risk'
    | '/advisor/students'
    | '/student/community'
    | '/student/companion'
    | '/student/journey'
    | '/student/profile'
    | '/student/readiness'
    | '/student/wellbeing'
    | '/advisor/'
    | '/student/'
    | '/advisor/students/$id'
    | '/student/readiness/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/advisor/interventions'
    | '/advisor/reports'
    | '/advisor/risk'
    | '/advisor/students'
    | '/student/community'
    | '/student/companion'
    | '/student/journey'
    | '/student/profile'
    | '/student/readiness'
    | '/student/wellbeing'
    | '/advisor'
    | '/student'
    | '/advisor/students/$id'
    | '/student/readiness/report'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/login'
    | '/signup'
    | '/student'
    | '/advisor/interventions'
    | '/advisor/reports'
    | '/advisor/risk'
    | '/advisor/students'
    | '/student/community'
    | '/student/companion'
    | '/student/journey'
    | '/student/profile'
    | '/student/readiness'
    | '/student/wellbeing'
    | '/advisor/'
    | '/student/'
    | '/advisor/students/$id'
    | '/student/readiness/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/student/wellbeing': {
      id: '/student/wellbeing'
      path: '/wellbeing'
      fullPath: '/student/wellbeing'
      preLoaderRoute: typeof StudentWellbeingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/readiness': {
      id: '/student/readiness'
      path: '/readiness'
      fullPath: '/student/readiness'
      preLoaderRoute: typeof StudentReadinessRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/journey': {
      id: '/student/journey'
      path: '/journey'
      fullPath: '/student/journey'
      preLoaderRoute: typeof StudentJourneyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/companion': {
      id: '/student/companion'
      path: '/companion'
      fullPath: '/student/companion'
      preLoaderRoute: typeof StudentCompanionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/community': {
      id: '/student/community'
      path: '/community'
      fullPath: '/student/community'
      preLoaderRoute: typeof StudentCommunityRouteImport
      parentRoute: typeof StudentRoute
    }
    '/advisor/students': {
      id: '/advisor/students'
      path: '/students'
      fullPath: '/advisor/students'
      preLoaderRoute: typeof AdvisorStudentsRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/risk': {
      id: '/advisor/risk'
      path: '/risk'
      fullPath: '/advisor/risk'
      preLoaderRoute: typeof AdvisorRiskRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/reports': {
      id: '/advisor/reports'
      path: '/reports'
      fullPath: '/advisor/reports'
      preLoaderRoute: typeof AdvisorReportsRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/interventions': {
      id: '/advisor/interventions'
      path: '/interventions'
      fullPath: '/advisor/interventions'
      preLoaderRoute: typeof AdvisorInterventionsRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/student/readiness/report': {
      id: '/student/readiness/report'
      path: '/report'
      fullPath: '/student/readiness/report'
      preLoaderRoute: typeof StudentReadinessReportRouteImport
      parentRoute: typeof StudentReadinessRoute
    }
    '/advisor/students/$id': {
      id: '/advisor/students/$id'
      path: '/$id'
      fullPath: '/advisor/students/$id'
      preLoaderRoute: typeof AdvisorStudentsIdRouteImport
      parentRoute: typeof AdvisorStudentsRoute
    }
  }
}

interface AdvisorStudentsRouteChildren {
  AdvisorStudentsIdRoute: typeof AdvisorStudentsIdRoute
}

const AdvisorStudentsRouteChildren: AdvisorStudentsRouteChildren = {
  AdvisorStudentsIdRoute: AdvisorStudentsIdRoute,
}

const AdvisorStudentsRouteWithChildren = AdvisorStudentsRoute._addFileChildren(
  AdvisorStudentsRouteChildren,
)

interface AdvisorRouteChildren {
  AdvisorInterventionsRoute: typeof AdvisorInterventionsRoute
  AdvisorReportsRoute: typeof AdvisorReportsRoute
  AdvisorRiskRoute: typeof AdvisorRiskRoute
  AdvisorStudentsRoute: typeof AdvisorStudentsRouteWithChildren
  AdvisorIndexRoute: typeof AdvisorIndexRoute
}

const AdvisorRouteChildren: AdvisorRouteChildren = {
  AdvisorInterventionsRoute: AdvisorInterventionsRoute,
  AdvisorReportsRoute: AdvisorReportsRoute,
  AdvisorRiskRoute: AdvisorRiskRoute,
  AdvisorStudentsRoute: AdvisorStudentsRouteWithChildren,
  AdvisorIndexRoute: AdvisorIndexRoute,
}

const AdvisorRouteWithChildren =
  AdvisorRoute._addFileChildren(AdvisorRouteChildren)

interface StudentReadinessRouteChildren {
  StudentReadinessReportRoute: typeof StudentReadinessReportRoute
}

const StudentReadinessRouteChildren: StudentReadinessRouteChildren = {
  StudentReadinessReportRoute: StudentReadinessReportRoute,
}

const StudentReadinessRouteWithChildren =
  StudentReadinessRoute._addFileChildren(StudentReadinessRouteChildren)

interface StudentRouteChildren {
  StudentCommunityRoute: typeof StudentCommunityRoute
  StudentCompanionRoute: typeof StudentCompanionRoute
  StudentJourneyRoute: typeof StudentJourneyRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentReadinessRoute: typeof StudentReadinessRouteWithChildren
  StudentWellbeingRoute: typeof StudentWellbeingRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCommunityRoute: StudentCommunityRoute,
  StudentCompanionRoute: StudentCompanionRoute,
  StudentJourneyRoute: StudentJourneyRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentReadinessRoute: StudentReadinessRouteWithChildren,
  StudentWellbeingRoute: StudentWellbeingRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
